import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'api_client.dart';
import 'sync_queue_manager.dart';

/// Durable local-first attendance operations.
/// A worker can have only one attendance record per business day.
class OfflineAttendanceService {
  static const String _prefix = 'attendance_local_v2_';
  static Future<int?> _userId() async { final p=await SharedPreferences.getInstance(); return p.getInt('user_id') ?? p.getInt('userId'); }
  static String _date(DateTime v) => '${v.year.toString().padLeft(4,'0')}-${v.month.toString().padLeft(2,'0')}-${v.day.toString().padLeft(2,'0')}';
  static String _identity(Map<String,dynamic> r,int uid){final e=r['employee_id']?.toString().trim()??'';final w=r['worker_id']?.toString().trim()??'';if(e.isNotEmpty)return 'employee:$e';if(w.isNotEmpty)return 'worker:$w';return 'user:$uid';}
  static String _recordKey(Map<String,dynamic> r,int uid)=>'${_identity(r,uid)}:${(r['attendance_date']?.toString()??'').split('T').first}';
  static Future<String> _key(int uid) async=>'$_prefix$uid';

  static Future<List<Map<String,dynamic>>> loadLocalRecords() async { final uid=await _userId();if(uid==null||uid<=0)return <Map<String,dynamic>>[];final p=await SharedPreferences.getInstance();final raw=p.getString(await _key(uid));if(raw==null||raw.isEmpty)return <Map<String,dynamic>>[];try{final d=jsonDecode(raw);if(d is! List)return <Map<String,dynamic>>[];return d.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();}catch(_){return <Map<String,dynamic>>[];} }

  static Future<void> _saveRecords(List<Map<String,dynamic>> records) async { final uid=await _userId();if(uid==null||uid<=0)return;final p=await SharedPreferences.getInstance();final out=<String,Map<String,dynamic>>{};for(final r in records){final k=_recordKey(r,uid);if(k.endsWith(':'))continue;out[k]=Map<String,dynamic>.from(r);}await p.setString(await _key(uid),jsonEncode(out.values.toList())); }

  static Future<Map<String,dynamic>?> _findTodayRecord({required int employeeId,int? workerId,required String date}) async { final records=await loadLocalRecords();for(final r in records){if((r['employee_id']?.toString()??'')==employeeId.toString()&&(r['worker_id']?.toString()??'')==(workerId?.toString()??'')&&(r['attendance_date']?.toString()??'').split('T').first==date)return Map<String,dynamic>.from(r);}return null; }

  static Future<void> _upsertLocal({required int employeeId,int? workerId,required String date,DateTime? checkIn,DateTime? checkOut,String? status,double? workingHours}) async { final records=await loadLocalRecords();final index=records.indexWhere((r)=>(r['employee_id']?.toString()??'')==employeeId.toString()&&(r['worker_id']?.toString()??'')==(workerId?.toString()??'')&&(r['attendance_date']?.toString()??'').split('T').first==date);final existing=index>=0?Map<String,dynamic>.from(records[index]):<String,dynamic>{};final merged=<String,dynamic>{...existing,'employee_id':employeeId,if(workerId!=null)'worker_id':workerId,'attendance_date':date,if(checkIn!=null)'check_in_time':checkIn.toUtc().toIso8601String(),if(checkOut!=null)'check_out_time':checkOut.toUtc().toIso8601String(),if(status!=null)'status':status.toUpperCase(),if(workingHours!=null)'working_hours':workingHours,'local_pending':true,'updated_at':DateTime.now().toUtc().toIso8601String()};if(index>=0)records[index]=merged;else records.add(merged);await _saveRecords(records); }

  /// Idempotent check-in. If stale UI calls checkIn while an active local
  /// check-in already exists, treat that call as the toggle's checkout action.
  static Future<bool> checkIn({required int employeeId,int? workerId}) async { final now=DateTime.now();final date=_date(now);final existing=await _findTodayRecord(employeeId:employeeId,workerId:workerId,date:date);if(existing!=null&&existing['check_in_time']!=null){if(existing['check_out_time']!=null)return true;return checkOut(employeeId:employeeId,workerId:workerId);}final operationId='ATT_IN_${workerId??employeeId}_$date';await _upsertLocal(employeeId:employeeId,workerId:workerId,date:date,checkIn:now,status:'PRESENT');final queued=await SyncQueueManager.enqueue('attendance_check_in',{'operation_id':operationId,'idempotency_key':operationId,'employee_id':employeeId,'worker_id':workerId,'attendance_date':date});if(!queued)throw StateError('Unable to persist attendance check-in to durable outbox');return true; }

  static Future<bool> checkOut({required int employeeId,int? workerId}) async { final now=DateTime.now();final date=_date(now);final existing=await _findTodayRecord(employeeId:employeeId,workerId:workerId,date:date);if(existing!=null&&existing['check_out_time']!=null)return true;DateTime? checkIn;final raw=existing?['check_in_time'];if(raw!=null)checkIn=DateTime.tryParse(raw.toString());final hours=checkIn==null?null:now.difference(checkIn.toLocal()).inSeconds/3600.0;final operationId='ATT_OUT_${workerId??employeeId}_$date';await _upsertLocal(employeeId:employeeId,workerId:workerId,date:date,checkOut:now,workingHours:hours,status:'PRESENT');final queued=await SyncQueueManager.enqueue('attendance_check_out',{'operation_id':operationId,'idempotency_key':operationId,'employee_id':employeeId,'worker_id':workerId,'attendance_date':date});if(!queued)throw StateError('Unable to persist attendance check-out to durable outbox');return true; }

  static Future<void> mergeRemoteRecords(List<Map<String,dynamic>> remoteRecords) async { if(remoteRecords.isEmpty)return;try{final uid=await _userId();if(uid==null||uid<=0)return;final local=await loadLocalRecords();final merged=<String,Map<String,dynamic>>{};for(final r in local){merged[_recordKey(r,uid)]=Map<String,dynamic>.from(r);}for(final server in remoteRecords){final k=_recordKey(server,uid);final previous=merged[k];merged[k]={...(previous??{}),...server,'local_pending':false,'synced_at':DateTime.now().toUtc().toIso8601String()};}await _saveRecords(merged.values.toList());}catch(e){if(kDebugMode)debugPrint('⚠️ Failed to cache remote attendance history: $e');} }

  static Future<void> reconcileFromBackend() async { final uid=await _userId();if(uid==null||uid<=0)return;try{final date=_date(DateTime.now());final response=await ApiClient.getJson('${ApiClient.attendancePrefix}/date/$date');if(response.statusCode!=200)return;final decoded=jsonDecode(response.body);if(decoded is! Map||decoded['records'] is! List)return;final remote=(decoded['records'] as List).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();if(remote.isEmpty)return;final local=await loadLocalRecords();final merged=<String,Map<String,dynamic>>{};for(final r in local){merged[_recordKey(r,uid)]=Map<String,dynamic>.from(r);}for(final server in remote){final k=_recordKey(server,uid);merged[k]={...(merged[k]??{}),...server,'local_pending':false,'synced_at':DateTime.now().toUtc().toIso8601String()};}await _saveRecords(merged.values.toList());}catch(e){if(kDebugMode)debugPrint('OfflineAttendance reconcile skipped: $e');} }

  static Future<void> markSynced({required int employeeId,int? workerId,required String date}) async {final records=await loadLocalRecords();for(int i=0;i<records.length;i++){final r=records[i];if((r['employee_id']?.toString()??'')==employeeId.toString()&&(r['worker_id']?.toString()??'')==(workerId?.toString()??'')&&(r['attendance_date']?.toString().split('T').first??'')==date){records[i]={...r,'local_pending':false,'synced_at':DateTime.now().toUtc().toIso8601String()};await _saveRecords(records);return;}}}
}
